### ISSUE TITLE
Make `yarn create` work

### ISSUE THREAD

**Issue by knowbody** [knowbody/crra#10]
Currently it throws an error when trying to run `yarn create reason-react-app MyApp` and then `yarn dev`:

![image](https://cloud.githubusercontent.com/assets/3802023/26786180/9a6c546a-49fd-11e7-95ab-c12fa6fd136d.png)

**Comment by jamesmcallister** [comment]
Looks like it's looking for `copy.js` which isn't there. Look [here](https://github.com/knowbody/crra/blob/aa18b1964cab73db798ceb155e30af11b26bab48/src/bsconfig.json#L19)

I get the same error.

**Comment by knowbody** [comment]
yeah I tried adding it back and I get:
`permisson denied`

![image](https://cloud.githubusercontent.com/assets/3802023/26787253/41160d1c-4a01-11e7-8068-24e7f7d0c03e.png)

**Comment by jamesmcallister** [comment]
Where is the `copy.js`file? Shouldn't it be in the repo?

**Comment by knowbody** [comment]
just added it back, I think it got removed during the transition to CLI

**Comment by knowbody** [comment]
It still throws `permission denied`, check this tweet from Jared:  https://twitter.com/jaredpalmer/status/871731955225808896

I just don't know how to add it

**Comment by jamesmcallister** [comment]
Could it be as simple as running `chmod u+x copy.js` before you publish to npm?

**Comment by jamesmcallister** [comment]
Also its seems to be complaining about no `webpack.config.js`

**Comment by knowbody** [comment]
ok, going to add it now... thank you

**Comment by knowbody** [comment]
@jamesmcallister I did the `chmod` but it seems like the issue stays there still, also added the webpack config back

**Comment by knowbody** [comment]
@msenevir any idea how to fix this? you worked on the testing so maybe you would be able to help with this one?

**Comment by msenevir** [comment]
can take a look. when i originally committed the script I had run `chmod a+x scripts/copy.js`

**Comment by knowbody** [comment]
@msenevir would be awesome! I tried running it, so did @jaredpalmer in #11 but still getting `permission denied`

**Comment by knowbody** [comment]
fixed by #14
