### ISSUE TITLE
Error when running CLI under node v8 - File argument must be a non-empty string

### ISSUE THREAD

**Issue by mlesk** [knowbody/crra#16]
Fails with node version 8 with error below. 
Runs fine with version 7.9.0.

![screenshot 2017-06-05 20 46 42](https://cloud.githubusercontent.com/assets/2768436/26809121/3f79d2d4-4a30-11e7-9444-0534de62a46b.jpg)

**Comment by knowbody** [comment]
this should be now fixed via #17 
try out the new release v0.1.10
