### ISSUE TITLE
bsb reporting is lost under webpack-dev-server

### ISSUE THREAD

**Issue by aweary** [knowbody/crra#2]
first off, congrats on the release! 🎉 

I've noticed that the `start` command (`npm run bsb-watch | npm run dev`)  is arranged in a way that causes only the webpack dev server output to be displayed. This means that any output from `bsb` is lost.

I think it's probably more valuable to see what `bsb` is reporting. Could this command be rearranged so that the `bsb` is displayed instead, or, better yet, what about a way to run and log output concurrently (in an organized way)?

**Comment by knowbody** [comment]
@aweary thanks! Yeah I noticed this as well, I'm actually working on the solution for the more visible error handling. I had a chat with @jordwalke and he suggested `berror` (which is included in [`reason-cli`](https://github.com/reasonml/reason-cli)) to me. It has a very nice way of displaying errors, and suggesting the correction. Something similar to what Elm has. 

If you want to try it out, install `react-cli` globally on your machine, and run:
`bsb -make-world -w 2>&1 | berror --path-to-refmttype refmttype` in one tab of the terminal and `webpack-dev-server` in the other.

As Jordan mentioned this works well most of the time but not always. Then you would fallback on the standard `bsb` errors. There's a room of improvement there for `berror`.

But what I'd like is something like `redbox-react` with the errors from `berror` displayed in the browser. So I don't need to check in terminal if the code actually compiled or not.

**Comment by knowbody** [comment]
I pushed the fix, but I'd like to still make this errors more visible. Will open a new issue
