### ISSUE TITLE
fetch example?

### ISSUE THREAD

**Issue by kenichi-asai** [knowbody/crra#27]
It would be great if you have an example that access a server using fetch (as an advanced example, perhaps).  I have been trying to write it myself but so far without success.  Meanwhile, is there such an example somewhere?  Having a list of links to useful standard examples would also help.

**Comment by kenichi-asai** [comment]
I just found a recently and nicely written article:
https://jamesfriend.com.au/a-first-reason-react-app-for-js-developers
which fulfills my original question.

**Comment by knowbody** [comment]
Yup, I asked James to PR in this repo to add these things to guides. Feel free to help if you'd like to, send the PR

**Comment by chenglou** [comment]
Glad to see this solved. Btw we've moved to https://github.com/reasonml-community/reason-scripts, which is basically a fork of create-react-app. Thanks for raising the issue =).

Closing!
