### ISSUE TITLE
Bucklescript status gets stuck at 'Compiling...' after error

### ISSUE THREAD

**Issue by jsdf** [knowbody/crra#33]
- add a syntax error
- wait for it to be displayed in the CRRA output
- fix the syntax error
- the Bucklescript status still displays 'Compiling...' even though subsequent changes have been successfully compiled

**Comment by knowbody** [comment]
can you have a look into this @tzilist, please?

**Comment by tzilist** [comment]
@knowbody sure thing!

**Comment by chenglou** [comment]
We've now moved to https://github.com/reasonml-community/reason-scripts, and this is solved. Sorry for the trouble.
