### ISSUE TITLE
React Native?

### ISSUE THREAD

**Issue by bstro** [knowbody/crra#36]
This looks awesome! How hard do you think it would be to get this going with react-native?

**Comment by knowbody** [comment]
I know that @ken_wheeler and @dabit3 were exploring that area, any thoughts Nader, Ken?

**Comment by dabit3** [comment]
@knowbody @bstro , Ken has a nice project going with navigation + other stuff, we're going to use that with a --native flag I believe. Look out for this pr in the coming week!

**Comment by chenglou** [comment]
Hey everyone, we've moved to https://github.com/reasonml-community/reason-scripts. That one's a legit fork of create-react-app, so we can probably more easily achieve create-reason-react-native-app (lol) though that, spiritually. cc @rrdelaney
