### ISSUE TITLE
yarn hangs trying to create a new project

### ISSUE THREAD

**Issue by nwaywood** [knowbody/crra#39]
![image](https://user-images.githubusercontent.com/3773641/27514592-9430e7a2-59d2-11e7-96fc-a35638c4f264.png)

Running macOS Sierra v10.12.3

**Comment by knowbody** [comment]
please try out what @bassjacob recommended in the README, and let me know if it helps or not:

> these steps might seem like they have frozen on slower computers. if it seems like one of the commands has frozen, please try re-running it adding --verbose to the command at the end to make sure it isn't just processing lots of information. if it does still look frozen, please let us know by opening an issue here

**Comment by nwaywood** [comment]
@knowbody I have already tried that as well, I get no extra output

![image](https://user-images.githubusercontent.com/3773641/27520833-4d98d1da-5a57-11e7-99fe-2f4a0e4954b0.png)

sorry I probably should have included that in the original issue.

Other information that might also be relevant:
npm version: `5.0.3`
node version: `7.7.4`
yarn version: `0.16.1`

**Comment by knowbody** [comment]
can you upgrade `yarn` to the latest version? I've just checked and works fine here, I'm on `yarn@0.24.6`

**Comment by nwaywood** [comment]
Just upgraded to `yarn@0.24.6` and still have the same issue. What version of `npm` and `node` are you on?

**Comment by knowbody** [comment]
npm: 5.0.3
node: 8.1.2

**Comment by nwaywood** [comment]
Ok I'm now on:

npm: 5.0.3
node: 8.1.2
yarn: 0.24.6

and it still hangs :/ any other ideas of what else I can try?

**Comment by knowbody** [comment]
you could try cloning the repo and going into `templates/basic` and trying to `yarn install` there or if that doesn't work try to `npm install` there, please let me know how it goes.

**Comment by nwaywood** [comment]
Ok `yarn install` in `templates/basic` also hangs but `npm install` works.

May I suggest changing `crra` to use `npm` for installation instead of `yarn`? It is obviously a lot more stable

**Comment by knowbody** [comment]
yeah we might need to do that. Do you mind creating a PR and also creating an issue about `yarn`? I will try to get someone from `yarn` team to take a look at it

**Comment by nwaywood** [comment]
Ok sure, I'll make a PR sometime today to switch to use `npm`. Regarding creating an issue for `yarn`, does this issue not suffice? I just renamed the title of the issue to make it more clear

**Comment by knowbody** [comment]
Thanks! Yeah this should be enough, thank you

**Comment by nwaywood** [comment]
Here is the PR: https://github.com/knowbody/crra/pull/41

**Comment by chenglou** [comment]
This is merged, so I'm closing this. Though we've moved to https://github.com/reasonml-community/reason-scripts already and it works with Yarn.

Thanks again for your contribution =)
