### ISSUE TITLE
BuckleScript fails to compile immediately after creating app

### ISSUE THREAD

**Issue by StevenLangbroek** [knowbody/crra#43]
I just freshly installed crra, reason-cli on Node 8 (tried Node 7 as well), several things happen that I think are faulty:

1. There's a compile error:

```bash
File "/Users/rg/Projects/playground/src/app.re", line 7, characters 15-17:
Error: This pattern matches values of type unit
       but a pattern was expected which matches values of type
         ('a, 'b) ReasonReact.self
ninja: build stopped: subcommand failed.
```

I'm trying to get started, but don't know enough about ReasonML yet to submit a PR to fix this.

2. I had to find this error by commenting the `clearConsole` function. The errors are hidden by other stuff.
3. Console still reports Bucklescript status as `Compilation success`.
4. Then got this error:

```bash
ERROR in multi webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./lib/js/src/index.js
Module not found: Error: Can't resolve './lib/js/src/index.js' in '/Users/rg/Projects/proto-crra'
 @ multi webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./lib/js/src/index.js
```

5. Annoyingly, webpack dev server stays active, so I have to manually shut down node processes, otherwise I get a `EADDRINUSE` error.

Being a total noob at ReasonML, what can I do to help?

**Comment by sgrove** [comment]
So the problem here is that crra relies on master HEAD for reason-react, which shuffled signatures around a bit recently (without releasing a new npm package, so docs aren't updated - people aren't expected to be using HEAD unless they're comfortable with constant breakage/tweaks).

To quote @rickyvetter:
> In the newest version of RR, state has been rolled into self... Basically all instances of state by itself have been removed. Can be accessed by destructuring self.

So two options:

1. Specify the stable version of `reason-react` ([0.1.5](https://www.npmjs.com/package/reason-react)) in place of https://github.com/knowbody/crra/blob/master/templates/basic/package.json#L35, and the code should work as is.

2. Bravely (foolishly?) push through, and update the code to this:

```reason
let click _event {ReasonReact.state: _state} => Js.log "clicked!";


/** The above is just a more idiomatic version of:
       let click _event self => {
         let _state = ReasonReact.(self.state);
         Js.log "clicked!"
       };
    */

let component = ReasonReact.statelessComponent "App";

let make ::title _children => {
  ...component,
  render: fun self =>
    <div className="App">
      <div className="App-header">
        <div
          onClick=(self.handle click)
          style=(
                  ReactDOMRe.Style.make
                    display::"flex" width::"200px" backgroundColor::"#db4d3f" cursor::"pointer" ()
                )>
          <svg className="App-logo" viewBox="0 0 841.9 595.3" alt="logo">
            <g fill="#fff">
              <path
                d="M666.3 296.5c0-32.5-40.7-63.3-103.1-82.4 14.4-63.6 8-114.2-20.2-130.4-6.5-3.8-14.1-5.6-22.4-5.6v22.3c4.6 0 8.3.9 11.4 2.6 13.6 7.8 19.5 37.5 14.9 75.7-1.1 9.4-2.9 19.3-5.1 29.4-19.6-4.8-41-8.5-63.5-10.9-13.5-18.5-27.5-35.3-41.6-50 32.6-30.3 63.2-46.9 84-46.9V78c-27.5 0-63.5 19.6-99.9 53.6-36.4-33.8-72.4-53.2-99.9-53.2v22.3c20.7 0 51.4 16.5 84 46.6-14 14.7-28 31.4-41.3 49.9-22.6 2.4-44 6.1-63.6 11-2.3-10-4-19.7-5.2-29-4.7-38.2 1.1-67.9 14.6-75.8 3-1.8 6.9-2.6 11.5-2.6V78.5c-8.4 0-16 1.8-22.6 5.6-28.1 16.2-34.4 66.7-19.9 130.1-62.2 19.2-102.7 49.9-102.7 82.3 0 32.5 40.7 63.3 103.1 82.4-14.4 63.6-8 114.2 20.2 130.4 6.5 3.8 14.1 5.6 22.5 5.6 27.5 0 63.5-19.6 99.9-53.6 36.4 33.8 72.4 53.2 99.9 53.2 8.4 0 16-1.8 22.6-5.6 28.1-16.2 34.4-66.7 19.9-130.1 62-19.1 102.5-49.9 102.5-82.3zm-130.2-66.7c-3.7 12.9-8.3 26.2-13.5 39.5-4.1-8-8.4-16-13.1-24-4.6-8-9.5-15.8-14.4-23.4 14.2 2.1 27.9 4.7 41 7.9zm-45.8 106.5c-7.8 13.5-15.8 26.3-24.1 38.2-14.9 1.3-30 2-45.2 2-15.1 0-30.2-.7-45-1.9-8.3-11.9-16.4-24.6-24.2-38-7.6-13.1-14.5-26.4-20.8-39.8 6.2-13.4 13.2-26.8 20.7-39.9 7.8-13.5 15.8-26.3 24.1-38.2 14.9-1.3 30-2 45.2-2 15.1 0 30.2.7 45 1.9 8.3 11.9 16.4 24.6 24.2 38 7.6 13.1 14.5 26.4 20.8 39.8-6.3 13.4-13.2 26.8-20.7 39.9zm32.3-13c5.4 13.4 10 26.8 13.8 39.8-13.1 3.2-26.9 5.9-41.2 8 4.9-7.7 9.8-15.6 14.4-23.7 4.6-8 8.9-16.1 13-24.1zM421.2 430c-9.3-9.6-18.6-20.3-27.8-32 9 .4 18.2.7 27.5.7 9.4 0 18.7-.2 27.8-.7-9 11.7-18.3 22.4-27.5 32zm-74.4-58.9c-14.2-2.1-27.9-4.7-41-7.9 3.7-12.9 8.3-26.2 13.5-39.5 4.1 8 8.4 16 13.1 24 4.7 8 9.5 15.8 14.4 23.4zM420.7 163c9.3 9.6 18.6 20.3 27.8 32-9-.4-18.2-.7-27.5-.7-9.4 0-18.7.2-27.8.7 9-11.7 18.3-22.4 27.5-32zm-74 58.9c-4.9 7.7-9.8 15.6-14.4 23.7-4.6 8-8.9 16-13 24-5.4-13.4-10-26.8-13.8-39.8 13.1-3.1 26.9-5.8 41.2-7.9zm-90.5 125.2c-35.4-15.1-58.3-34.9-58.3-50.6 0-15.7 22.9-35.6 58.3-50.6 8.6-3.7 18-7 27.7-10.1 5.7 19.6 13.2 40 22.5 60.9-9.2 20.8-16.6 41.1-22.2 60.6-9.9-3.1-19.3-6.5-28-10.2zM310 490c-13.6-7.8-19.5-37.5-14.9-75.7 1.1-9.4 2.9-19.3 5.1-29.4 19.6 4.8 41 8.5 63.5 10.9 13.5 18.5 27.5 35.3 41.6 50-32.6 30.3-63.2 46.9-84 46.9-4.5-.1-8.3-1-11.3-2.7zm237.2-76.2c4.7 38.2-1.1 67.9-14.6 75.8-3 1.8-6.9 2.6-11.5 2.6-20.7 0-51.4-16.5-84-46.6 14-14.7 28-31.4 41.3-49.9 22.6-2.4 44-6.1 63.6-11 2.3 10.1 4.1 19.8 5.2 29.1zm38.5-66.7c-8.6 3.7-18 7-27.7 10.1-5.7-19.6-13.2-40-22.5-60.9 9.2-20.8 16.6-41.1 22.2-60.6 9.9 3.1 19.3 6.5 28.1 10.2 35.4 15.1 58.3 34.9 58.3 50.6-.1 15.7-23 35.6-58.4 50.6zM320.8 78.4z"
              />
              <circle cx="420.9" cy="296.5" r="45.7" />
              <path d="M520.5 78.1z" />
            </g>
          </svg>
        </div>
        <h2 style=(ReactDOMRe.Style.make marginLeft::"30px" fontSize::"2em" ())>
          (ReasonReact.stringToElement title)
        </h2>
      </div>
      <p className="App-intro">
        (ReasonReact.stringToElement "To get started, edit ")
        <code> (ReasonReact.stringToElement "src/app.re") </code>
        (ReasonReact.stringToElement " and save to reload.")
      </p>
    </div>
};
```
(note there are only two changes above: to the signature of `render` (only takes `self` now) and to `click` (only takes `event` and `self` now))

**Comment by StevenLangbroek** [comment]
Thanks so much!

Should I submit this as a PR so the code runs as is, or should crra locks its deps? Sounds like this could cause a lot of noise in Issues when more people start using this?

I think the bigger issue is also that this error was swallowed and webpack-dev-server kept running. How can I help fixing that?

**Comment by sgrove** [comment]
@knowbody should lock crra deps down (it'll definitely save issues in the future) to `0.1.5`, master isn't document yet.

I'm not sure about #3 in your list, but it's important - our frontend designer/dev hit it as well.

#5 seems like it should be possibly to fix, but I'm not much of a node dev, sadly. I hit it as well, so if you're familiar, please take a stab at it!

**Comment by chenglou** [comment]
Waaaait people actually rely on rr master? We should change it to stable. Master isn't ready yet

Sorry for the problem.  Also, you can always try the minimal boilerplate with`bsb -init my_app -theme react`

**Comment by chenglou** [comment]
@StevenLangbroek I forgot I had push right to this repo. I've nailed down the reason-react version for now.

**Comment by knowbody** [comment]
thanks @chenglou

**Comment by StevenLangbroek** [comment]
Thanks @chenglou! 

@knowbody would you like me to take a stab at catching bucklescript errors and displaying them? Or will this be tackled by switching to `bs-loader`?

**Comment by chenglou** [comment]
Hey @StevenLangbroek! Your ping might have drowned in my email notifications. We've now moved to https://github.com/reasonml-community/reason-scripts

As for error messages, stayed tuned for the next BS release! It'll be included. If you can't wait, you can check out here: https://github.com/BuckleScript/bucklescript/tree/master/jscomp/super_errors. Though adding one isn't as trivial just yet. You can see the recent PRs I've made to that repo.
