### ISSUE TITLE
Webpack Server keeps running after a failure

### ISSUE THREAD

**Issue by anmonteiro** [knowbody/crra#44]
I think the use of `child_process` in `scripts/startDev.js` is responsible.

When `npm start` fails (e.g. BuckleScript compilation failure) the spawned processes keep running.

Doing proper housekeeping would make up for a better dev experience.

**Comment by chenglou** [comment]
@anmonteiro I guess you might know this already, but we've moved to https://github.com/reasonml-community/reason-scripts. Sorry for the trouble!
