### ISSUE TITLE
Please either maintain or deprecate this

### ISSUE THREAD

**Issue by glennsl** [knowbody/crra#49]
It's broken and it's throwing a lot of people off right now.

If you're one of those thrown off, here's what you should use instead:
* The official guide: https://reasonml.github.io/guide/javascript/quickstart/
* The community-maintained create-react-app: https://github.com/reasonml-community/reason-scripts

**Comment by chenglou** [comment]
It's my fault. We're halfway deprecating it a few days ago and I got busy and this got neglected. I've gotten publishing rights and officially deprecated this
